version: '3.9'

# To access data postgres and redis writes within container from host machine
volumes:
  postgres_data: {}
  redis_data: {}
  gem_cache: {}
  node_modules: {}

services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-ssidecisions}
      POSTGRES_DB: ${PG_DB:-sample_development}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  webpack:
    image: heroku-sample-app
    ports:
      - '3035:3035'
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      RAILS_ENV: ${RAILS_ENV:-development}
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    volumes:
      - .:/var/www/heroku-sample
      - gem_cache:/usr/local/bundle
      - node_modules:/var/www/heroku-sample/node_modules
    command: ./bin/webpack-dev-server

  app:
    stdin_open: true # docker run -i
    tty: true # docker run -t
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      args:
        RAILS_ENV: ${RAILS_ENV:-development}
    image: heroku-sample-app
    depends_on:
      - postgres
      - redis
    environment:
      RAILS_ENV: ${RAILS_ENV:-development}
      WEBPACKER_DEV_SERVER_HOST: webpack
      MAILER_HOST: mailcatcher
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/var/www/heroku-sample
      - gem_cache:/usr/local/bundle
      - node_modules:/var/www/heroku-sample/node_modules
    entrypoint: docker/app/entrypoint.sh
    command: bundle exec rails server -b 0.0.0.0

  worker:
    image: heroku-sample-app
    depends_on:
      - postgres
      - redis
    environment:
      RAILS_ENV: ${RAILS_ENV:-development}
    env_file: .env
    volumes:
      - .:/var/www/heroku-sample
      - gem_cache:/usr/local/bundle
      - node_modules:/var/www/heroku-sample/node_modules
    command: bundle exec sidekiq -C config/sidekiq.yml

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
      args:
        RAILS_ENV: ${RAILS_ENV:-development}
    image: heroku-sample-web
    depends_on:
      - app
    ports:
      - 80:80
    volumes:
      - ./public:/var/www/heroku-sample/public
